function fname = gen_filename(group_data, speed)
  fname = sprintf('section%d_group%d_%s_%s_%dms', ...
    group_data.section,                           ...
    group_data.group,                             ...
    group_data.angles,                            ...
    group_data.type,                              ...
    speed);
end
